* What is this?

  A fork of the [[http://lml2.b9.com][LML2]] Common Lisp Markup Language by Kevin Rosenberg that
  aims to fully support [[http://html5rocks.com][HTML5]].

** HTML5 Document type

   The *HTML5* document type is supported, i.e., =<!DOCTYPE html>=. 

** Supported elements

   + <article> =:article=

   + <aside> =:aside=

   + <audio> =:audio=

   + <figure> =:figure=

   + <figcaption> =:figcaption=

   + <footer> =:footer=

   + <header> =:header=

   + <hgroup> =:hgroup=

   + <mark> =:mark=

   + <nav> =:nav=

   + <section> =:section=

   + <source> =:source=

   + <time> =:time=

   + <video> =:video=

   This fork was created from the [[http://packages.debian.org/sid/cl-lml2][Debian unstable]] cl-lml2 package.

** Specifying HTML5 documents

   To use the HTML5 document type give as first argument to
   =html-file-page= the following:

   =(html-file-page (<other args> :format :html5 <more args> )=

** Language specification

   There's also support for language specification, i.e., ISO code and
   writing direction. By default the language is *en-US* and the
   direction *ltr* (left-to-right). The language is specified as a
   keyword argument in the argument list to =html-file-page=.

   For specifying european portuguese do: 

   =(html-file-page (<filename> :format :html5 :language "pt-PT")= 

   Note that this specification is valid for other document types also.

** XHTML encoding

   Besides supporting HTML5 this fork also supports specifying the
   encoding through the keyword argument =:encoding= to =html-file-page=.

   To declare a *XHTML 1.0 Strict* document you would give:

   =(html-file-page (<other args> :format :xhtml-strict :encoding :utf-8 <more args>)=
